/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  AssessorFabLike,
  AssessorFabLikeInterface,
} from "../AssessorFabLike";

const _abi = [
  {
    constant: false,
    inputs: [],
    name: "newAssessor",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class AssessorFabLike__factory {
  static readonly abi = _abi;
  static createInterface(): AssessorFabLikeInterface {
    return new utils.Interface(_abi) as AssessorFabLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AssessorFabLike {
    return new Contract(address, _abi, signerOrProvider) as AssessorFabLike;
  }
}
