/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  CollectorFabLike,
  CollectorFabLikeInterface,
} from "../CollectorFabLike";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "newCollector",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class CollectorFabLike__factory {
  static readonly abi = _abi;
  static createInterface(): CollectorFabLikeInterface {
    return new utils.Interface(_abi) as CollectorFabLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CollectorFabLike {
    return new Contract(address, _abi, signerOrProvider) as CollectorFabLike;
  }
}
