/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  CoordinatorFabLike,
  CoordinatorFabLikeInterface,
} from "../CoordinatorFabLike";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "newCoordinator",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class CoordinatorFabLike__factory {
  static readonly abi = _abi;
  static createInterface(): CoordinatorFabLikeInterface {
    return new utils.Interface(_abi) as CoordinatorFabLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CoordinatorFabLike {
    return new Contract(address, _abi, signerOrProvider) as CoordinatorFabLike;
  }
}
