/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  EpochTrancheLike,
  EpochTrancheLikeInterface,
} from "../EpochTrancheLike";

const _abi = [
  {
    constant: false,
    inputs: [],
    name: "closeEpoch",
    outputs: [
      {
        internalType: "uint256",
        name: "totalSupply",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalRedeem",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "uint256",
        name: "epochID",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "supplyFulfillment_",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "redeemFulfillment_",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "tokenPrice_",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "epochSupplyCurrency",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "epochRedeemCurrency",
        type: "uint256",
      },
    ],
    name: "epochUpdate",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class EpochTrancheLike__factory {
  static readonly abi = _abi;
  static createInterface(): EpochTrancheLikeInterface {
    return new utils.Interface(_abi) as EpochTrancheLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EpochTrancheLike {
    return new Contract(address, _abi, signerOrProvider) as EpochTrancheLike;
  }
}
