/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  NAVFeedFabLike,
  NAVFeedFabLikeInterface,
} from "../NAVFeedFabLike";

const _abi = [
  {
    constant: false,
    inputs: [],
    name: "newFeed",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class NAVFeedFabLike__factory {
  static readonly abi = _abi;
  static createInterface(): NAVFeedFabLikeInterface {
    return new utils.Interface(_abi) as NAVFeedFabLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NAVFeedFabLike {
    return new Contract(address, _abi, signerOrProvider) as NAVFeedFabLike;
  }
}
