/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ReserveFabLike,
  ReserveFabLikeInterface,
} from "../ReserveFabLike";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "newReserve",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ReserveFabLike__factory {
  static readonly abi = _abi;
  static createInterface(): ReserveFabLikeInterface {
    return new utils.Interface(_abi) as ReserveFabLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ReserveFabLike {
    return new Contract(address, _abi, signerOrProvider) as ReserveFabLike;
  }
}
